#!/bin/sh
# generate new version header file
exec > new.version.f90
date=`date -R`
host=`hostname -s`
name="$1"
shift
version="$1"
shift
flags="$@"
cat <<EOF
!> Module to provide program version info.
!!
!! This module is autogenerated from a script in order
!! to contain various pieces of information that is only
!! available at compile time. These are the compilation 
!! data and the compiler flags, but also information about
!! the version and the last commit to the source code 
!! management system.
module header

contains

!> Print the program version banner
subroutine version
  use io, only : stdout,separator
  implicit none

  write (stdout,*) '=================='
  write (stdout,*) ' ${name} v${version} '
  write (stdout,*) '=================='
  write (stdout,*) separator
  write (stdout,*) 'Compile date : ${date} on ${host}'
  write (stdout,*) 'Compile flags: ${flags}'
  write (stdout,*) separator
EOF
git log -n 1 --pretty="     write (stdout,*) 'Last commit  : %H'"
git log -n 1 --pretty="     write (stdout,*) 'Commit date  : %aD'" 
git log -n 1 --pretty="     write (stdout,*) 'Commit author: %an <%ae>'" 
cat <<EOF
     write (stdout,*) separator
end subroutine version
end module header
EOF

mv new.version.f90 version.f90
